spring:
  application:
    name:
      api-gateway
#api gateway configs
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - StripPrefix=2
#            - RedirectTo=302, https://github.com/shah8375033
            - name: LoggingOrdersFilter
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - StripPrefix=2
eureka:
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka



